name: Speakance
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    iOS: "17.0"
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.example.speakance
    SWIFT_VERSION: 5.9
targets:
  Speakance:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: Assets.xcassets
        buildPhase: resources
      - path: PrivacyInfo.xcprivacy
        buildPhase: resources
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_KEY_CFBundleDisplayName: Speakance
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIRequiredDeviceCapabilities:
          - arm64
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_NSMicrophoneUsageDescription: Speakance uses the microphone so you can record expense entries by voice.
        INFOPLIST_KEY_NSSpeechRecognitionUsageDescription: Speakance may use speech recognition to transcribe your expense recordings.
    info:
      path: Info.plist
      properties:
        SUPABASE_URL: https://pyramncggeecifntwlop.supabase.co
        SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5cmFtbmNnZ2VlY2lmbnR3bG9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4MDYzNTAsImV4cCI6MjA4NzM4MjM1MH0.Zd185VRjDEJUYD1CltQywVZKp0hMVL5sQ0O57aJuCXY
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIApplicationSupportsIndirectInputEvents: true

  SpeakanceTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: Speakance
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
